### ISSUE TITLE
name wrong

### ISSUE THREAD

**Issue by lynn-jie** [devstark-com/vue-epub-reader#10]
themes: {
					white: {
						body: {
							color: '#000000',
							background: '#ffffff'
						},
						name: 'БЕЛЫЙ'
					},
					beige: {
						body: {
							color: '#000000',
							background: '#f3e8d2'
						},
						name: 'БЕЖЕВЫЙ'
					},
					night: {
						body: {
							color: '#ffffff',
							background: '#4a4a4a'
						},
						name: 'НОЧНОЙ'
					}
				},

**Comment by nobilix** [comment]
fixed, also check out an example in the updated readme 
https://github.com/devstark-com/vue-epub-reader#example
